// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/cases": {
    params: {};
  };
  "/admin/cases/new": {
    params: {};
  };
  "/admin/cases/:id": {
    params: {
      "id": string;
    };
  };
  "/admin/cases/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/mobile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/admin/cases" | "/admin/cases/new" | "/admin/cases/:id" | "/admin/cases/:id/edit" | "/mobile";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/cases" | "/admin/cases/new" | "/admin/cases/:id" | "/admin/cases/:id/edit";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.cases._index.tsx": {
    id: "routes/admin.cases._index";
    page: "/admin/cases";
  };
  "routes/admin.cases.new.tsx": {
    id: "routes/admin.cases.new";
    page: "/admin/cases/new";
  };
  "routes/admin.cases.$id.tsx": {
    id: "routes/admin.cases.$id";
    page: "/admin/cases/:id";
  };
  "routes/admin.cases.$id.edit.tsx": {
    id: "routes/admin.cases.$id.edit";
    page: "/admin/cases/:id/edit";
  };
  "routes/mobile.tsx": {
    id: "routes/mobile";
    page: "/mobile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.cases._index": typeof import("./app/routes/admin.cases._index.tsx");
  "routes/admin.cases.new": typeof import("./app/routes/admin.cases.new.tsx");
  "routes/admin.cases.$id": typeof import("./app/routes/admin.cases.$id.tsx");
  "routes/admin.cases.$id.edit": typeof import("./app/routes/admin.cases.$id.edit.tsx");
  "routes/mobile": typeof import("./app/routes/mobile.tsx");
};